api = "0.7"

[buildpack]
  homepage = "https://github.com/initializ-buildpacks/node-engine"
  id = "initializ-buildpacks/node-engine"
  name = "Initializ Buildpack for Node Engine"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/initializ-buildpacks/node-engine/blob/main/LICENSE"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "bin/optimize-memory", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    node = "20.*.*"

  

  [[metadata.dependencies]]
    checksum = "sha256:3fe4ec5d70c8b4ffc1461dec83ab23fc70124e137c4cbbe1ccc9d6ae6ec04a7d"
    cpe = "cpe:2.3:a:nodejs:node.js:20.10.0:*:*:*:*:*:*:*"
    deprecation_date = "2026-04-30T00:00:00Z"
    id = "node"
    licenses = ["0BSD", "Apache-2.0", "Artistic-2.0", "BSD-2-Clause", "BSD-3-Clause", "BSD-4-Clause", "BSD-Source-Code", "CC0-1.0", "ECL-2.0", "ICU", "MIT", "MIT-0", "SHL-0.5", "SHL-0.51", "Unicode-TOU"]
    name = "Node Engine"
    purl = "pkg:generic/node@v20.10.0?checksum=3fe4ec5d70c8b4ffc1461dec83ab23fc70124e137c4cbbe1ccc9d6ae6ec04a7d&download_url=https://nodejs.org/dist/v20.10.0/node-v20.10.0-linux-x64.tar.xz"
    source = "https://nodejs.org/dist/v20.10.0/node-v20.10.0-linux-x64.tar.xz"
    source-checksum = "sha256:3fe4ec5d70c8b4ffc1461dec83ab23fc70124e137c4cbbe1ccc9d6ae6ec04a7d"
    stacks = ["*"]
    strip-components = 1
    uri = "https://nodejs.org/dist/v20.10.0/node-v20.10.0-linux-x64.tar.xz"
    version = "20.10.0"

 

  [[metadata.dependency-constraints]]
    constraint = "20.*"
    id = "node"
    patches = 1



[[stacks]]
  id = "*"
